name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        env:
          SSH_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
          SSH_PORT: ${{ secrets.HOSTINGER_PORT }}
          SSH_HOST: ${{ secrets.HOSTINGER_HOST }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          printf "%s\n" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Ensure rsync installed
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Deploy files to Hostinger with rsync
        env:
          SSH_USER: ${{ secrets.HOSTINGER_USER }}
          SSH_HOST: ${{ secrets.HOSTINGER_HOST }}
          SSH_PORT: ${{ secrets.HOSTINGER_PORT }}
          DEST_PATH: ${{ secrets.HOSTINGER_PATH }}
        run: |
          ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH OK'"

          rsync -avz --delete --exclude='.git' --exclude='.github' \
            -e "ssh -p $SSH_PORT" \
            ./ $SSH_USER@$SSH_HOST:$DEST_PATH
